#!/bin/bash
if [ -e /proc/stb/video/avshutdown ]; then
echo "avshutdown found"

cat << 'EOF' > /usr/bin/enigma2_pre_start.sh
echo "down" > /proc/stb/video/avshutdown && echo "up" > /proc/stb/video/avshutdown
EOF
chmod 755 /usr/bin/enigma2_pre_start.sh
echo "workaround applied successfully, rebooting"
reboot
else
echo "sorry, cant use workaround on this system"
fi
### thx to DarkStarXxX ###
